# Generated by Django 5.1.15 on 2026-08-25 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pools', '0001_initial'),
        ('teams', '0001_initial'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='players/photos/')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('extra_info', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('available', 'Available'), ('pooled', 'In Pool'), ('in_auction', 'Currently Up for Bidding'), ('sold', 'Sold'), ('unsold', 'Unsold')], default='available', max_length=16)),
                ('sold_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='pools.pool')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='tournaments.position')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='teams.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
