# Generated by Django 5.1.15 on 2026-08-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='low_priority',
            field=models.BooleanField(default=False, help_text='Set when an unsold player is returned to their original pool — they are skipped in random draws until every normal-priority player in that pool is gone.'),
        ),
    ]
