# Generated by Django 5.1.15 on 2026-08-25 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='tournaments/covers/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('setup', 'Setup'), ('live', 'Live'), ('completed', 'Completed')], default='draft', max_length=16)),
                ('num_teams', models.PositiveIntegerField(default=0)),
                ('players_per_team_min', models.PositiveIntegerField(default=1, help_text='Minimum squad size a team must reach for a complete roster')),
                ('players_per_team_max', models.PositiveIntegerField(default=20, help_text='Maximum squad size a team can build')),
                ('default_team_budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bid_timer_seconds', models.PositiveIntegerField(default=15, help_text='Countdown per player, resets on each new bid')),
                ('bid_timer_extend_seconds', models.PositiveIntegerField(default=15, help_text='Seconds added when admin manually extends the timer')),
                ('public_guest_link_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BidIncrementRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('to_amount', models.DecimalField(blank=True, decimal_places=2, help_text="Leave blank for 'and above'", max_digits=12, null=True)),
                ('increment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='increment_rules', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['from_amount'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['order', 'name'],
                'unique_together': {('tournament', 'name')},
            },
        ),
    ]
