# Generated by Django 5.1.15 on 2026-08-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_tournament_end_date_tournament_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='theme_club_logo',
            field=models.ImageField(blank=True, null=True, upload_to='tournaments/theme/'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='theme_primary_logo',
            field=models.ImageField(blank=True, null=True, upload_to='tournaments/theme/'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='theme_sponsor_logo',
            field=models.ImageField(blank=True, null=True, upload_to='tournaments/theme/'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='themed_display_enabled',
            field=models.BooleanField(default=False, help_text='Show a branded big-screen display (with the logos below) instead of the generic one.'),
        ),
    ]
