# Generated by Django 5.1.15 on 2026-08-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_tournament_theme_club_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='bid_cooldown_seconds',
            field=models.PositiveIntegerField(default=3, help_text='Short freeze after each bid before another bid can land, so everyone has time to register the new price. Set to 0 to disable.'),
        ),
    ]
