# Generated by Django 5.1.15 on 2026-08-26 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_tournament_result_display_seconds'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentSponsorLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tournaments/theme/sponsors/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_logos', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
