# Generated by Django 5.1.15 on 2026-08-25 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pool_type', models.CharField(choices=[('normal', 'Normal'), ('unsold_round', 'Unsold Re-round')], default='normal', max_length=16)),
                ('round_number', models.PositiveIntegerField(default=1, help_text='1 = first pass, 2+ = unsold re-rounds')),
                ('order', models.PositiveIntegerField(default=0, help_text='Sequence in which pools are auctioned')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pools', to='tournaments.position')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
